### ISSUE TITLE
关于部署

### ISSUE THREAD

**Issue by AbstractWorld** [iaoongin/i-share#1]
请问博主这个项目可以部署至服务器吗？
因为粗略看了一下好像没有html文件

**Comment by iaoongin** [comment]
可以的，html在docs文件夹里
https://github.com/iaoongin/i-share/blob/master/docs/index.html

**Comment by undolog** [comment]
好的，谢谢兄弟


> 可以的，html在docs文件夹里
> https://github.com/iaoongin/i-share/blob/master/docs/index.html
好的，谢谢兄弟

**Comment by iaoongin** [comment]
> 好的，谢谢兄弟
> 
> > 可以的，html在docs文件夹里
> > https://github.com/iaoongin/i-share/blob/master/docs/index.html
> > 好的，谢谢兄弟

不客气
